# YAML configuration file for attiny-0series high mem
#
# Copyright 2026 Clement Savergne <csavergne@yahoo.com>
#
# This file is part of yasim-avr.
#
# yasim-avr is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# yasim-avr is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with yasim-avr.  If not, see <http://www.gnu.org/licenses/>.


#This file contains the common configuration keys for attiny-0series models
#with flash mem > 8kb and double word IVT


---
inherits: attiny-0series

interrupts:
    vector_size: 4

    vectors:
        - RESET
        - CRCSCAN
        - BOD
        - PORTA
        - PORTB
        - PORTC
        - RTC_CNT
        - RTC_PIT
        - TCA0_OVF
        - TCA0_HUNF
        - TCA0_CMP0
        - TCA0_CMP1
        - TCA0_CMP2
        - TCB0
        - AC0
        - ADC0_RESRDY
        - ADC0_WCOMP
        - TWI0_TWIS
        - TWI0_TWIM
        - SPI0
        - USART0_RXC
        - USART0_DRE
        - USART0_TXC
        - NVMCTRL_EE

    sleep_mask:
        Idle:       [ 0xFF, 0xFF, 0xFF ]
        Standby:    [ 0xFF, 0xE0, 0x01 ]
        PowerDown:  [ 0xBF, 0x00, 0x00 ]
