# Device model configuration database
#
# Copyright 2023-2026 Clement Savergne <csavergne@yahoo.com>
#
# This file is part of yasim-avr.
#
# yasim-avr is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# yasim-avr is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with yasim-avr.  If not, see <http://www.gnu.org/licenses/>.

---
dev_mega_0series:
    - XT/atmega0-series/atmega808
    - XT/atmega0-series/atmega809
    - XT/atmega0-series/atmega1608
    - XT/atmega0-series/atmega1609
    - XT/atmega0-series/atmega3208
    - XT/atmega0-series/atmega3209
    - XT/atmega0-series/atmega4808
    - XT/atmega0-series/atmega4809

dev_tiny_0series:
    - XT/attiny0-series/attiny202
    - XT/attiny0-series/attiny204
    - XT/attiny0-series/attiny402
    - XT/attiny0-series/attiny404
    - XT/attiny0-series/attiny406
    - XT/attiny0-series/attiny804
    - XT/attiny0-series/attiny806
    - XT/attiny0-series/attiny807
    - XT/attiny0-series/attiny1604
    - XT/attiny0-series/attiny1606
    - XT/attiny0-series/attiny1607

dev_megaxx8:
    - AVRe/atmega48-88-168-328/atmega48
    - AVRe/atmega48-88-168-328/atmega48p
    - AVRe/atmega48-88-168-328/atmega88
    - AVRe/atmega48-88-168-328/atmega88p
    - AVRe/atmega48-88-168-328/atmega168
    - AVRe/atmega48-88-168-328/atmega168p
    - AVRe/atmega48-88-168-328/atmega328
    - AVRe/atmega48-88-168-328/atmega328p

dev_tinyx4:
    - AVRe/attiny24-44-84/attiny24
    - AVRe/attiny24-44-84/attiny44
    - AVRe/attiny24-44-84/attiny84
