name: Build

on:
  workflow_dispatch:

  push:
    branches:
      - cibuildwheel

jobs:
  Build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: install libelf (Windows)
        if: matrix.os == 'windows-latest'
        run: C:\\msys64\\msys2_shell -no-start -defterm -c "pacman -S --noconfirm mingw-w64-x86_64-libelf"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_BUILD_FRONTEND: build

          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_24
          CIBW_BEFORE_BUILD_LINUX: 'apt-get install libelf-dev'

          CIBW_CONFIG_SETTINGS_WINDOWS: --build-option="--compiler=mingw32"
          CIBW_ENVIRONMENT_WINDOWS: PATH="C:\\msys64\\mingw64\\bin;$PATH"

        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
